name = "SlimCheck"
version = "0.1.0"
defaultTargets = ["SlimCheck"]
testRunner = "Test"

[[lean_lib]]
name = "Test"

[[lean_lib]]
name = "SlimCheck"

[[require]]
name = "batteries"
scope = "leanprover-community"
version = "git#v4.13.0-rc3"
